# Generated by Django 6.0.2 on 2026-02-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('lease_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('leasor_name', models.CharField(max_length=255)),
                ('contract_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Amendment', 'Amendment')], default='Active', max_length=20)),
            ],
            options={
                'db_table': 'lease_contract',
            },
        ),
        migrations.CreateModel(
            name='LeaseFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('present_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('other_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dismantling_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('home_currency', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lease_term', models.IntegerField()),
                ('lease_period', models.CharField(choices=[('Year', 'Year'), ('Month', 'Month')], max_length=10)),
                ('discount_rate', models.FloatField()),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='lease.leasecontract')),
            ],
            options={
                'db_table': 'lease_financial',
            },
        ),
        migrations.CreateModel(
            name='LeasePaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_period', models.CharField(choices=[('Year', 'Year'), ('Month', 'Month')], max_length=10)),
                ('computation', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year'), ('Quaterly', 'Quaterly'), ('Half of Year', 'Half of Year')], max_length=20)),
                ('changing_date', models.DateField(blank=True, null=True)),
                ('changing_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_term', to='lease.leasecontract')),
            ],
            options={
                'db_table': 'lease_payment_term',
            },
        ),
    ]
