# Generated by Django 6.0.2 on 2026-02-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasefinancial',
            name='extensions',
            field=models.BooleanField(default=False),
        ),
    ]
