# Generated by Django 6.0.2 on 2026-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_leasefinancial_extensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasefinancial',
            name='extensions',
        ),
        migrations.AddField(
            model_name='leasefinancial',
            name='changing_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='leasefinancial',
            name='changing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasefinancial',
            name='computation',
            field=models.CharField(choices=[('Month', 'Month'), ('Year', 'Year'), ('Quaterly', 'Quaterly'), ('Half of Year', 'Half of Year')], default='Year', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leasefinancial',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leasefinancial',
            name='payment_period',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month')], default='Year', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leasefinancial',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LeasePaymentTerm',
        ),
    ]
