# Generated by Django 6.0.2 on 2026-02-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0003_remove_leasefinancial_extensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasefinancial',
            name='present_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20),
        ),
    ]
